RenderSettings:
  PostProcessing:
    IsBloomEnabled: true
    BloomThreshold: 1.04999995
    BloomMagnitude: 2
    BloomBlurSigma: 0.5
    AdaptationRate: 0.5
    KeyValue: 0.200000003
    MinExposure: 1.5
    MaxExposure: 2