RenderSettings:
  PostProcessing:
    IsBloomEnabled: false
    BloomThreshold: 3
    BloomMagnitude: 0.5
    BloomBlurSigma: 0.800000012
    AdaptationRate: 0.5
    KeyValue: 0.200000003
    MinExposure: 0.5
    MaxExposure: 1.5